---
coredns_go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

coredns_go_arch: "{{ coredns_go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
coredns_download_filename: coredns_{{ coredns_version }}_linux_{{ coredns_go_arch }}
