- name: Copy vlan device
  ansible.builtin.template:
    src: vlan.netdev.j2
    dest: /etc/systemd/network/20-{{ device_name }}.netdev
    mode: '0644'
  vars: &block_vars
    device_name: "{{ interface.device_name }}.{{ vlan.id }}"
    id: "{{ vlan.id }}"
    ip: "{{ vlan.ip }}"

- name: Copy vlan network
  ansible.builtin.template:
    src: network.j2
    dest: /etc/systemd/network/30-{{ device_name }}.network
    mode: '0644'
  vars: *block_vars
