---
- name: Ensure firewalld is installed
  ansible.builtin.apt:
    name: firewalld
    state: present

- name: Configure zones
  ansible.builtin.include_tasks: zone.yml
  loop: "{{ firewalld_zones | dict2items }}"
  loop_control:
    loop_var: zone
