---
- name: Ensure ppp and pppoe are installed
  ansible.builtin.apt:
    name: ppp,pppoe
    state: present

- name: Add username and password to chap-secret
  ansible.builtin.lineinfile:
    path: /etc/ppp/chap-secrets
    line: '"{{ pppoe_username }}" * "{{ pppoe_password }}"'
    state: present
  loop:
    - /etc/ppp/chap-secrets
    - /etc/ppp/pap-secrets

- name: Copy pppoe setting
  ansible.builtin.template:
    src: provider.j2
    dest: /etc/ppp/peers/{{ pppoe_interface_name }}
    mode: '0600'

- name: Copy pppoe systemd service
  ansible.builtin.template:
    src: pppoe.service.j2
    dest: /etc/systemd/system/{{ pppoe_service_name }}.service
    mode: '0644'

- name: Ensure pppoe service is started
  ansible.builtin.systemd_service:
    name: "{{ pppoe_service_name }}"
    state: started
    enabled: true
    daemon_reload: true
